#!/bin/sh
set -e

case "$1" in
    configure)
        update-alternatives --install /usr/share/gcin/ogg gcin-voice /usr/share/gcin-voice/ogg 10
        update-alternatives --install /usr/share/hime/ogg hime-voice /usr/share/gcin-voice/ogg 10
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

#DEBHELPER#

exit 0
